### ISSUE TITLE
api缺失

### ISSUE THREAD

**Issue by muskf** [CubeWhyMC/website#1]
> URL: https://launcherupdates.lunarclientcdn.com/latest.yml?noCache=1hcm29ms1
> 状态: Completed
> 方法: GET
> 协议: HTTP/1.1
> Code: 200

```
version: 3.1.0
files:
  - url: Lunar Client v3.1.0.exe
    sha512: tAVAX5aB0gGurM5RbHZ9Z5dPCxHLfZTGHXvlnvfuNRQGq2imQPp9HhxAKzMfgeIG3iM4ig7E6BlUw1QoL9PzSA==
path: Lunar Client v3.1.0.exe
sha512: tAVAX5aB0gGurM5RbHZ9Z5dPCxHLfZTGHXvlnvfuNRQGq2imQPp9HhxAKzMfgeIG3iM4ig7E6BlUw1QoL9PzSA==
packages:
  ia32:
    size: 80598744
    sha512: L9oPeyxzlembBZwR7KFi+hlZU7cjXYZ3+XC6VjB71muqR4ACpgD7bufBVd0GK35BpNNqO1kT6WWP2Lq8mcz4Tg==
    blockMapSize: 86538
    path: launcher-3.1.0-ia32.nsis.7z
    file: launcher-3.1.0-ia32.nsis.7z
  x64:
    size: 85220313
    sha512: u4KsrizmeNyV++ddfmwrnZ/G6f12MCoYDoBLkebbsgx5Ct/svILu01VxT17nsdJvgKzrrnegYFLQRGaRSZz2vQ==
    blockMapSize: 89725
    path: launcher-3.1.0-x64.nsis.7z
    file: launcher-3.1.0-x64.nsis.7z
releaseDate: '2023-09-18T21:06:32.093Z'
```
